name: Curl Request on Merge to Master

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: trigger ci
        run: |
          curl -X POST http://test.terasky-devops.com:8080/ci/trigger \
            -H "Content-Type: application/json" \
            -d '{"hash_key": "${{ secrets.SHA_KEY }}"}'
